# Generated by Django 5.1.5 on 2025-02-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectosRecreativos', '0002_contratista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratista',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='cedula',
        ),
        migrations.AddField(
            model_name='contratista',
            name='empresa',
            field=models.CharField(default='Independiente', max_length=100, verbose_name='Empresa'),
        ),
    ]
