# Generated by Django 5.1.5 on 2025-02-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectosRecreativos', '0004_alter_cliente_apellido_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueRecreativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
