# Generated by Django 5.1.5 on 2025-02-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectosRecreativos', '0005_parquerecreativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('En Planificación', 'En Planificación'), ('En Construcción', 'En Construcción'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectosRecreativos.contratista')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectosRecreativos.parquerecreativo')),
            ],
        ),
    ]
