# Generated by Django 5.1.5 on 2025-02-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectosRecreativos', '0006_proyectoconstruccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='contratista/'),
        ),
    ]
